<h1>Ejercicio #1: Data Cleaning & Transformation | FIFA 21 Players Dataset</h1>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

In [83]:
# importamos el dataset
fifa_players = pd.read_csv('datasets/fifa21_raw_data.csv',low_memory=False)
fifa_players.head(10)

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
5,https://cdn.sofifa.com/players/188/545/21_60.png,Robert Lewandowski,http://sofifa.com/player/188545/robert-lewando...,Poland,ST,R. Lewandowski,31,91,91,\n\n\n\nFC Bayern München\n2014 ~ 2023\n\n,...,High,Medium,4 ★,78,91,78,85,43,82,\n182
6,https://cdn.sofifa.com/players/231/747/21_60.png,Kylian Mbappé,http://sofifa.com/player/231747/kylian-mbappe/...,France,ST LW RW,K. Mbappé,21,90,95,\n\n\n\nParis Saint-Germain\n2018 ~ 2022\n\n,...,High,Low,3 ★,96,86,78,91,39,76,\n646
7,https://cdn.sofifa.com/players/212/831/21_60.png,Alisson Ramses Becker,http://sofifa.com/player/212831/alisson-ramses...,Brazil,GK,Alisson,27,90,91,\n\n\n\nLiverpool\n2018 ~ 2024\n\n,...,Medium,Medium,3 ★,86,88,85,89,51,91,\n79
8,https://cdn.sofifa.com/players/209/331/21_60.png,Mohamed Salah,http://sofifa.com/player/209331/mohamed-salah/...,Egypt,RW,M. Salah,28,90,90,\n\n\n\nLiverpool\n2017 ~ 2023\n\n,...,High,Medium,3 ★,93,86,81,90,45,75,\n164
9,https://cdn.sofifa.com/players/208/722/21_60.png,Sadio Mané,http://sofifa.com/player/208722/sadio-mane/210...,Senegal,LW,S. Mané,28,90,90,\n\n\n\nLiverpool\n2016 ~ 2023\n\n,...,High,Medium,3 ★,94,85,80,90,44,76,\n170

In [84]:
#fifa_players.shape
fifa_players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              18979 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

In [96]:
fifa_players.describe()

,Age,↓OVA,POT,ID,BOV,Growth,Attacking,Crossing,Finishing,Heading Accuracy,...,Base Stats,PAC,SHO,PAS,DRI,DEF,PHY,Joined_Day,Joined_Month,Joined_Year
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,25.194583,65.718636,71.136098,226404.790242,66.751620,5.417461,248.938616,49.688551,45.842932,51.941883,...,355.703040,67.454239,53.457716,57.681069,62.875494,49.865904,64.368618,10.190421,5.659097,2018.288108
std,4.710753,6.968999,6.114176,27141.673349,6.747017,5.663954,74.299764,18.131334,19.566978,17.293626,...,40.762282,10.678058,13.827229,10.081914,9.927875,16.442730,9.601665,9.979814,3.094827,2.086655
min,16.000000,47.000000,47.000000,41.000000,48.000000,0.000000,42.000000,6.000000,3.000000,5.000000,...,232.000000,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000,1.000000,1.000000,1998.000000
25%,21.000000,61.000000,67.000000,210135.000000,62.000000,0.000000,222.000000,38.000000,30.000000,44.000000,...,327.000000,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000,1.000000,2.000000,2018.000000
50%,25.000000,66.000000,71.000000,232424.000000,67.000000,4.000000,263.000000,54.000000,49.000000,55.000000,...,356.000000,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000,7.000000,7.000000,2019.000000
75%,29.000000,70.000000,75.000000,246925.500000,71.000000,9.000000,297.000000,63.000000,62.000000,64.000000,...,384.000000,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000,18.000000,8.000000,2020.000000
max,53.000000,93.000000,95.000000,259216.000000,93.000000,26.000000,437.000000,94.000000,95.000000,93.000000,...,498.000000,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000,31.000000,12.000000,2020.000000

In [86]:
#Do the height and wight columns have the appropiate data types?
fifa_players['Height']

0         5'7"
1         6'2"
2         6'2"
3        5'11"
4         5'9"
         ...
18974    5'10"
18975     5'7"
18976    5'10"
18977     5'9"
18978     5'9"
Name: Height, Length: 18979, dtype: object

In [87]:
#Eliminamos columnas del dataset
fifa_players.drop(fifa_players.columns [[3,4,18]],axis = 1,inplace = True)
fifa_players.head(10)

,photoUrl,LongName,playerUrl,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,High,Medium,5 ★,91,85,86,94,36,59,\n273
5,https://cdn.sofifa.com/players/188/545/21_60.png,Robert Lewandowski,http://sofifa.com/player/188545/robert-lewando...,R. Lewandowski,31,91,91,\n\n\n\nFC Bayern München\n2014 ~ 2023\n\n,188545,"6'0""",...,High,Medium,4 ★,78,91,78,85,43,82,\n182
6,https://cdn.sofifa.com/players/231/747/21_60.png,Kylian Mbappé,http://sofifa.com/player/231747/kylian-mbappe/...,K. Mbappé,21,90,95,\n\n\n\nParis Saint-Germain\n2018 ~ 2022\n\n,231747,"5'10""",...,High,Low,3 ★,96,86,78,91,39,76,\n646
7,https://cdn.sofifa.com/players/212/831/21_60.png,Alisson Ramses Becker,http://sofifa.com/player/212831/alisson-ramses...,Alisson,27,90,91,\n\n\n\nLiverpool\n2018 ~ 2024\n\n,212831,"6'3""",...,Medium,Medium,3 ★,86,88,85,89,51,91,\n79
8,https://cdn.sofifa.com/players/209/331/21_60.png,Mohamed Salah,http://sofifa.com/player/209331/mohamed-salah/...,M. Salah,28,90,90,\n\n\n\nLiverpool\n2017 ~ 2023\n\n,209331,"5'9""",...,High,Medium,3 ★,93,86,81,90,45,75,\n164
9,https://cdn.sofifa.com/players/208/722/21_60.png,Sadio Mané,http://sofifa.com/player/208722/sadio-mane/210...,S. Mané,28,90,90,\n\n\n\nLiverpool\n2016 ~ 2023\n\n,208722,"5'9""",...,High,Medium,3 ★,94,85,80,90,44,76,\n170

In [88]:
#validamos nulos
fifa_players.isnull().sum()

photoUrl     0
LongName     0
playerUrl    0
Name         0
Age          0
            ..
PAS          0
DRI          0
DEF          0
PHY          0
Hits         0
Length: 74, dtype: int64

In [89]:
fifa_players['Joined']

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974     Aug 1, 2020
18975     Aug 1, 2020
18976    Jul 13, 2018
18977     Aug 1, 2020
18978     Jan 1, 2020
Name: Joined, Length: 18979, dtype: object

In [92]:
#transformamos la columna Joined a date
#también almacenamos en columnas separadas los datos de día mes y año
x= j_d= j_m= j_y=[]
for item in fifa_players['Joined']:
#     x.append(datetime.strptime(item,"%b %d, %Y").date())
    j_date=datetime.strptime(item,"%b %d, %Y").date()
    x.append(j_date)
    j_d.append(j_date.day)
    j_m.append(j_date.month)
    j_y.append(j_date.year)

In [95]:
fifa_players['Joined']=x
fifa_players['Joined_Day']=j_d
fifa_players['Joined_Month']=j_m
fifa_players['Joined_Year']=j_y

In [97]:
#separamos la info de Team y Contract en diferentes columnas
team=[]
contract=[]
for element in fifa_players['Team & Contract']:
    team.append(list(filter(None,element.split("\n")))[0])
    contract.append(list(filter(None,element.split("\n")))[1])

In [105]:
fifa_players['Team']=team
fifa_players['Contract']=contract

In [126]:
fifa_players.groupby(fifa_players['Wage']).count()

,photoUrl,LongName,playerUrl,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,PAS,DRI,DEF,PHY,Hits,Joined_Day,Joined_Month,Joined_Year,Team,Contract
Wage,,,,,,,,,,,,,,,,,,,,,
€0,238,238,238,238,238,238,238,238,238,238,...,238,238,238,238,238,238,238,238,238,238
€100K,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13
€105K,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
€10K,201,201,201,201,201,201,201,201,201,201,...,201,201,201,201,201,201,201,201,201,201
€110K,12,12,12,12,12,12,12,12,12,12,...,12,12,12,12,12,12,12,12,12,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
€96K,6,6,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
€97K,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
€98K,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
€99K,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
€9K,367,367,367,367,367,367,367,367,367,367,...,367,367,367,367,367,367,367,367,367,367

In [125]:
fifa_players['Wage']

       photoUrl  LongName  playerUrl  Name  Age  ↓OVA  POT  Team & Contract  \
Wage
€0          238       238        238   238  238   238  238              238
€100K        13        13         13    13   13    13   13               13
€105K        15        15         15    15   15    15   15               15
€10K        201       201        201   201  201   201  201              201
€110K        12        12         12    12   12    12   12               12
...         ...       ...        ...   ...  ...   ...  ...              ...
€96K          6         6          6     6    6     6    6                6
€97K          2         2          2     2    2     2    2                2
€98K          4         4          4     4    4     4    4                4
€99K          1         1          1     1    1     1    1                1
€9K         367       367        367   367  367   367  367              367

        ID  Height  ...  PAS  DRI  DEF  PHY  Hits  Joined_Day  Joined_Month  \
Wage                ...
€0     238     238  ...  238  238  238  238   238         238           238
€100K   13      13  ...   13   13   13   13    13          13            13
€105K   15      15  ...   15   15   15   15    15          15            15
€10K   201     201  ...  201  201  201  201   201         201           201
€110K   12      12  ...   12   12   12   12    12          12            12
...    ...     ...  ...  ...  ...  ...  ...   ...         ...           ...
€96K     6       6  ...    6    6    6    6     6           6             6
€97K     2       2  ...    2    2    2    2     2           2             2
€98K     4       4  ...    4    4    4    4     4           4             4
€99K     1       1  ...    1    1    1    1     1           1             1
€9K    367     367  ...  367  367  367  367   367         367           367

       Joined_Year  Team  Contract
Wage
€0             238   238       238
€100K           13    13        13
€105K           15    15        15
€10K           201   201       201
€110K           12    12        12
...            ...   ...       ...
€96K             6     6         6
€97K             2     2         2
€98K             4     4         4
€99K             1     1         1
€9K            367   367       367

[141 rows x 78 columns]

In [133]:
#Convertimos el salario a int(EUROS)
int_wage=[]
for wage in fifa_players['Wage']:
    wage=wage.replace('€','')
    wage=wage.replace('K','000')    
    int_wage.append(int(wage))

In [134]:
fifa_players['Wage_E']=int_wage
fifa_players.describe()

,Age,↓OVA,POT,ID,BOV,Growth,Attacking,Crossing,Finishing,Heading Accuracy,...,PAC,SHO,PAS,DRI,DEF,PHY,Joined_Day,Joined_Month,Joined_Year,Wage_E
count,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,...,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000,18979.000000
mean,25.194583,65.718636,71.136098,226404.790242,66.751620,5.417461,248.938616,49.688551,45.842932,51.941883,...,67.454239,53.457716,57.681069,62.875494,49.865904,64.368618,10.190421,5.659097,2018.288108,8796.129933
std,4.710753,6.968999,6.114176,27141.673349,6.747017,5.663954,74.299764,18.131334,19.566978,17.293626,...,10.678058,13.827229,10.081914,9.927875,16.442730,9.601665,9.979814,3.094827,2.086655,19537.282500
min,16.000000,47.000000,47.000000,41.000000,48.000000,0.000000,42.000000,6.000000,3.000000,5.000000,...,25.000000,16.000000,25.000000,25.000000,12.000000,28.000000,1.000000,1.000000,1998.000000,0.000000
25%,21.000000,61.000000,67.000000,210135.000000,62.000000,0.000000,222.000000,38.000000,30.000000,44.000000,...,61.000000,44.000000,51.000000,57.000000,35.000000,58.000000,1.000000,2.000000,2018.000000,1000.000000
50%,25.000000,66.000000,71.000000,232424.000000,67.000000,4.000000,263.000000,54.000000,49.000000,55.000000,...,68.000000,56.000000,58.000000,64.000000,53.000000,65.000000,7.000000,7.000000,2019.000000,3000.000000
75%,29.000000,70.000000,75.000000,246925.500000,71.000000,9.000000,297.000000,63.000000,62.000000,64.000000,...,75.000000,64.000000,64.000000,69.000000,63.000000,71.000000,18.000000,8.000000,2020.000000,8000.000000
max,53.000000,93.000000,95.000000,259216.000000,93.000000,26.000000,437.000000,94.000000,95.000000,93.000000,...,96.000000,93.000000,93.000000,95.000000,91.000000,91.000000,31.000000,12.000000,2020.000000,560000.000000

In [149]:
# plt.figure(figsize=(15,10))
# plt.hist(fifa_players['Wage'],bins=20)
# plt.show()

In [159]:
x=fifa_players['Hits'].apply(lambda item: item.replace('\n',''))

In [162]:
fifa_players['Hits_C']=x
fifa_players.head()

,photoUrl,LongName,playerUrl,Name,Age,↓OVA,POT,Team & Contract,ID,Height,...,DEF,PHY,Hits,Joined_Day,Joined_Month,Joined_Year,Team,Contract,Wage_E,Hits_C
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,38,65,\n372,1,7,2004,FC Barcelona,2004 ~ 2021,560000,372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,35,77,\n344,10,7,2018,Juventus,2018 ~ 2022,220000,344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,52,90,\n86,16,7,2014,Atlético Madrid,2014 ~ 2023,125000,86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,64,78,\n163,30,8,2015,Manchester City,2015 ~ 2023,370000,163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,36,59,\n273,3,8,2017,Paris Saint-Germain,2017 ~ 2022,270000,273